// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EventType defines the type of event
type EventType int32

const (
	EventType_Create EventType = 0
	EventType_Delete EventType = 1
	EventType_Update EventType = 2
)

var EventType_name = map[int32]string{
	0: "Create",
	1: "Delete",
	2: "Update",
}

var EventType_value = map[string]int32{
	"Create": 0,
	"Delete": 1,
	"Update": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

// Service represents a go-micro service
type Service struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Endpoints            []*Endpoint       `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Nodes                []*Node           `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Options              *Options          `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Service) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *Service) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Service) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Node represents the node the service is on
type Node struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port                 int64             `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Endpoint is a endpoint provided by a service
type Endpoint struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Request              *Value            `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Response             *Value            `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{2}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Endpoint) GetRequest() *Value {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Endpoint) GetResponse() *Value {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Endpoint) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Value is an opaque value for a request or response
type Value struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Values               []*Value `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{3}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Value) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Value) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

// Options are registry options
type Options struct {
	Ttl                  int64    `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{4}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *Options) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

// Result is returns by the watcher
type Result struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Service              *Service `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{5}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Result) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Result) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{6}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type GetRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Options              *Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{7}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *GetRequest) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type GetResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{8}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type ListRequest struct {
	Options              *Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{9}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type ListResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{10}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type WatchRequest struct {
	// service is optional
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Options              *Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchRequest) Reset()         { *m = WatchRequest{} }
func (m *WatchRequest) String() string { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()    {}
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{11}
}

func (m *WatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchRequest.Unmarshal(m, b)
}
func (m *WatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchRequest.Marshal(b, m, deterministic)
}
func (m *WatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchRequest.Merge(m, src)
}
func (m *WatchRequest) XXX_Size() int {
	return xxx_messageInfo_WatchRequest.Size(m)
}
func (m *WatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchRequest proto.InternalMessageInfo

func (m *WatchRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *WatchRequest) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Event is registry event
type Event struct {
	// Event Id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type of event
	Type EventType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.EventType" json:"type,omitempty"`
	// unix timestamp of event
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// service entry
	Service              *Service `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{12}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_Create
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type MarkRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkRequest) Reset()         { *m = MarkRequest{} }
func (m *MarkRequest) String() string { return proto.CompactTextString(m) }
func (*MarkRequest) ProtoMessage()    {}
func (*MarkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{13}
}

func (m *MarkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkRequest.Unmarshal(m, b)
}
func (m *MarkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkRequest.Marshal(b, m, deterministic)
}
func (m *MarkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkRequest.Merge(m, src)
}
func (m *MarkRequest) XXX_Size() int {
	return xxx_messageInfo_MarkRequest.Size(m)
}
func (m *MarkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkRequest proto.InternalMessageInfo

func (m *MarkRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ResetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{14}
}

func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (m *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(m, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

func (m *ResetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServicesRequest) Reset()         { *m = GetServicesRequest{} }
func (m *GetServicesRequest) String() string { return proto.CompactTextString(m) }
func (*GetServicesRequest) ProtoMessage()    {}
func (*GetServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{15}
}

func (m *GetServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServicesRequest.Unmarshal(m, b)
}
func (m *GetServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServicesRequest.Marshal(b, m, deterministic)
}
func (m *GetServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServicesRequest.Merge(m, src)
}
func (m *GetServicesRequest) XXX_Size() int {
	return xxx_messageInfo_GetServicesRequest.Size(m)
}
func (m *GetServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServicesRequest proto.InternalMessageInfo

type GetServicesResponse struct {
	Services             map[string]uint64 `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetServicesResponse) Reset()         { *m = GetServicesResponse{} }
func (m *GetServicesResponse) String() string { return proto.CompactTextString(m) }
func (*GetServicesResponse) ProtoMessage()    {}
func (*GetServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{16}
}

func (m *GetServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServicesResponse.Unmarshal(m, b)
}
func (m *GetServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServicesResponse.Marshal(b, m, deterministic)
}
func (m *GetServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServicesResponse.Merge(m, src)
}
func (m *GetServicesResponse) XXX_Size() int {
	return xxx_messageInfo_GetServicesResponse.Size(m)
}
func (m *GetServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServicesResponse proto.InternalMessageInfo

func (m *GetServicesResponse) GetServices() map[string]uint64 {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.EventType", EventType_name, EventType_value)
	proto.RegisterType((*Service)(nil), "proto.Service")
	proto.RegisterMapType((map[string]string)(nil), "proto.Service.MetadataEntry")
	proto.RegisterType((*Node)(nil), "proto.Node")
	proto.RegisterMapType((map[string]string)(nil), "proto.Node.MetadataEntry")
	proto.RegisterType((*Endpoint)(nil), "proto.Endpoint")
	proto.RegisterMapType((map[string]string)(nil), "proto.Endpoint.MetadataEntry")
	proto.RegisterType((*Value)(nil), "proto.Value")
	proto.RegisterType((*Options)(nil), "proto.Options")
	proto.RegisterType((*Result)(nil), "proto.Result")
	proto.RegisterType((*EmptyResponse)(nil), "proto.EmptyResponse")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto.RegisterType((*ListRequest)(nil), "proto.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "proto.ListResponse")
	proto.RegisterType((*WatchRequest)(nil), "proto.WatchRequest")
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*MarkRequest)(nil), "proto.MarkRequest")
	proto.RegisterType((*ResetRequest)(nil), "proto.ResetRequest")
	proto.RegisterType((*GetServicesRequest)(nil), "proto.GetServicesRequest")
	proto.RegisterType((*GetServicesResponse)(nil), "proto.GetServicesResponse")
	proto.RegisterMapType((map[string]uint64)(nil), "proto.GetServicesResponse.ServicesEntry")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 770 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5d, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x93, 0x38, 0x3f, 0x93, 0x34, 0x0d, 0xdb, 0x0a, 0xb9, 0x51, 0x8b, 0x82, 0x55, 0xa1,
	0xa8, 0x12, 0x2d, 0x4a, 0xa9, 0x68, 0xcb, 0x23, 0x0d, 0x7d, 0xa1, 0x80, 0x16, 0x0a, 0xcf, 0xa6,
	0x1e, 0x51, 0xab, 0x89, 0x6d, 0xbc, 0xdb, 0x48, 0x39, 0x00, 0x77, 0xe0, 0x0c, 0x9c, 0x80, 0x2b,
	0x70, 0x13, 0x8e, 0x81, 0x76, 0x3d, 0xeb, 0x38, 0x69, 0x1a, 0xc4, 0xdf, 0x53, 0x66, 0xe7, 0x7f,
	0xbe, 0xf9, 0xc6, 0x81, 0x56, 0x82, 0x1f, 0x03, 0x21, 0x93, 0xc9, 0x6e, 0x9c, 0x44, 0x32, 0x62,
	0xb6, 0xfe, 0x71, 0xbf, 0x16, 0xa1, 0xfa, 0x06, 0x93, 0x71, 0x70, 0x81, 0x8c, 0x41, 0x39, 0xf4,
	0x46, 0xe8, 0x58, 0x5d, 0xab, 0x57, 0xe7, 0x5a, 0x66, 0x0e, 0x54, 0xc7, 0x98, 0x88, 0x20, 0x0a,
	0x9d, 0xa2, 0x56, 0x9b, 0x27, 0x3b, 0x84, 0xda, 0x08, 0xa5, 0xe7, 0x7b, 0xd2, 0x73, 0x4a, 0xdd,
	0x52, 0xaf, 0xd1, 0xdf, 0x4c, 0x53, 0xef, 0x52, 0xbe, 0xdd, 0x33, 0x32, 0x0f, 0x42, 0x99, 0x4c,
	0x78, 0xe6, 0xcd, 0x1e, 0x42, 0x1d, 0x43, 0x3f, 0x8e, 0x82, 0x50, 0x0a, 0xa7, 0xac, 0x43, 0x57,
	0x29, 0x74, 0x40, 0x7a, 0x3e, 0xf5, 0x60, 0xf7, 0xc1, 0x0e, 0x23, 0x1f, 0x85, 0x63, 0x6b, 0xd7,
	0x06, 0xb9, 0xbe, 0x8c, 0x7c, 0xe4, 0xa9, 0x85, 0xf5, 0xa0, 0x1a, 0xc5, 0x32, 0x88, 0x42, 0xe1,
	0x54, 0xba, 0x56, 0xaf, 0xd1, 0x6f, 0x91, 0xd3, 0xab, 0x54, 0xcb, 0x8d, 0xb9, 0xf3, 0x14, 0x56,
	0x66, 0xda, 0x62, 0x6d, 0x28, 0x5d, 0xe1, 0x84, 0x66, 0x56, 0x22, 0x5b, 0x07, 0x7b, 0xec, 0x0d,
	0xaf, 0x91, 0x06, 0x4e, 0x1f, 0xc7, 0xc5, 0x43, 0xcb, 0xfd, 0x66, 0x41, 0x59, 0x95, 0x65, 0x2d,
	0x28, 0x06, 0x3e, 0xc5, 0x14, 0x03, 0x5f, 0xa1, 0xe4, 0xf9, 0x7e, 0x82, 0x42, 0x18, 0x94, 0xe8,
	0xa9, 0x30, 0x8d, 0xa3, 0x44, 0x3a, 0xa5, 0xae, 0xd5, 0x2b, 0x71, 0x2d, 0xb3, 0x83, 0x1c, 0x72,
	0xe9, 0xf8, 0x1b, 0xb9, 0x99, 0x6e, 0x83, 0xed, 0xef, 0x5a, 0xff, 0x61, 0x41, 0xcd, 0x80, 0xbb,
	0x70, 0xd1, 0x0f, 0xa0, 0x9a, 0xe0, 0xa7, 0x6b, 0x14, 0x52, 0x07, 0x37, 0xfa, 0x4d, 0xea, 0xe9,
	0x9d, 0xca, 0xc1, 0x8d, 0x91, 0xf5, 0xa0, 0x96, 0xa0, 0x88, 0xa3, 0x50, 0xa0, 0x1e, 0x6a, 0xde,
	0x31, 0xb3, 0xb2, 0xa3, 0x1b, 0x63, 0x6e, 0xcd, 0x6d, 0xf9, 0xff, 0x8c, 0x7a, 0x0e, 0xb6, 0x6e,
	0x65, 0xe1, 0x98, 0x0c, 0xca, 0x72, 0x12, 0x9b, 0x28, 0x2d, 0xb3, 0x6d, 0xa8, 0xe8, 0x68, 0x41,
	0x3c, 0x9e, 0x1d, 0x88, 0x6c, 0xee, 0x3e, 0x54, 0x89, 0x4d, 0xaa, 0x1b, 0x29, 0x87, 0x3a, 0x6f,
	0x89, 0x2b, 0x91, 0xdd, 0x85, 0x8a, 0x1f, 0x8d, 0xbc, 0xc0, 0x5c, 0x09, 0xbd, 0xdc, 0x4b, 0xa8,
	0x70, 0x14, 0xd7, 0x43, 0xa9, 0x3c, 0xbc, 0x0b, 0x15, 0x4e, 0xed, 0xd0, 0x4b, 0x51, 0x57, 0xa4,
	0xf7, 0x42, 0xb8, 0xb7, 0x66, 0xaf, 0x88, 0x1b, 0x33, 0xdb, 0x84, 0xba, 0x0c, 0x46, 0x28, 0xa4,
	0x37, 0x8a, 0x89, 0x4f, 0x53, 0x85, 0xbb, 0x0a, 0x2b, 0x83, 0x51, 0x2c, 0x27, 0x9c, 0xe0, 0x77,
	0x5f, 0x03, 0x9c, 0xa2, 0xe4, 0xb4, 0x36, 0x67, 0x5a, 0x26, 0xad, 0x9f, 0xa5, 0xcd, 0xdd, 0x4e,
	0x71, 0xe9, 0xed, 0xb8, 0x47, 0xd0, 0xd0, 0x19, 0x69, 0xbf, 0x3b, 0x50, 0xa3, 0x1c, 0xc2, 0xb1,
	0x34, 0x70, 0xf3, 0xad, 0x67, 0x76, 0xf7, 0x09, 0x34, 0x5e, 0x04, 0x22, 0xeb, 0x26, 0x57, 0xd3,
	0x5a, 0x5e, 0xf3, 0x18, 0x9a, 0x69, 0xe0, 0x1f, 0x14, 0xe5, 0xd0, 0x7c, 0xef, 0xc9, 0x8b, 0xcb,
	0x7f, 0x89, 0xc1, 0x67, 0x0b, 0xec, 0xc1, 0x18, 0x43, 0x79, 0xe3, 0x1b, 0xb0, 0x9d, 0x63, 0x56,
	0xab, 0xdf, 0x36, 0x54, 0x57, 0xbe, 0x6f, 0x27, 0x31, 0x12, 0xd7, 0x96, 0x2e, 0x31, 0x4f, 0x86,
	0xf2, 0x52, 0x32, 0xb8, 0x5b, 0xd0, 0x38, 0xf3, 0x92, 0x2b, 0x33, 0xda, 0x5c, 0x33, 0xee, 0x3d,
	0x68, 0x72, 0x14, 0xd3, 0xf5, 0xcf, 0xdb, 0xd7, 0x81, 0x9d, 0xa2, 0xa4, 0xac, 0x82, 0xbc, 0xdc,
	0x2f, 0x16, 0xac, 0xcd, 0xa8, 0x09, 0xf4, 0x93, 0x1b, 0xa0, 0xf7, 0xa8, 0xaf, 0x05, 0xde, 0xa6,
	0x57, 0x41, 0x47, 0x6d, 0x22, 0xd5, 0x51, 0xcf, 0x98, 0x7e, 0x75, 0xd4, 0xe5, 0xdc, 0x51, 0xef,
	0xec, 0x41, 0x3d, 0x83, 0x92, 0x01, 0x54, 0x9e, 0x25, 0xe8, 0x49, 0x6c, 0x17, 0x94, 0x7c, 0x82,
	0x43, 0x94, 0xd8, 0xb6, 0x94, 0x7c, 0x1e, 0xfb, 0x4a, 0x5f, 0xec, 0x7f, 0x2f, 0x41, 0x8d, 0xd3,
	0x5f, 0x1e, 0x3b, 0xd0, 0xb7, 0x60, 0xfe, 0xe7, 0xee, 0x4c, 0x9b, 0xa7, 0xc9, 0x3b, 0x2c, 0xaf,
	0xa2, 0x03, 0x2a, 0xb0, 0xbe, 0x49, 0x81, 0x09, 0x9b, 0xdb, 0x44, 0x67, 0xdd, 0x2c, 0x78, 0xe6,
	0xe8, 0x0a, 0xec, 0x31, 0xc0, 0x09, 0x26, 0xbf, 0x1b, 0x75, 0x94, 0xd2, 0xdc, 0xe0, 0xc3, 0x4c,
	0x3f, 0xb9, 0xa3, 0xe9, 0xac, 0xcd, 0xe8, 0xb2, 0xd0, 0x3d, 0xb0, 0x35, 0xcb, 0x99, 0xb1, 0xe7,
	0x39, 0xdf, 0x59, 0x21, 0x65, 0xfa, 0x15, 0x72, 0x0b, 0x8f, 0x2c, 0xd6, 0x87, 0xb2, 0xa2, 0x4e,
	0x56, 0x23, 0xc7, 0xa3, 0x25, 0x53, 0xd9, 0x9a, 0x4f, 0x59, 0x91, 0x3c, 0xbb, 0x6e, 0x8d, 0x7a,
	0xae, 0x3f, 0x18, 0xd9, 0x50, 0x1b, 0x8b, 0x48, 0x93, 0x66, 0xe8, 0xdc, 0xce, 0x27, 0xb7, 0xf0,
	0xa1, 0xa2, 0x8d, 0xfb, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xfe, 0x6a, 0x7e, 0xc4, 0x08,
	0x00, 0x00,
}
